### ISSUE TITLE
FFI unwind safety

### ISSUE THREAD

**Issue by Mart-Bogdan** [Michael-F-Bryan/thin-trait-objects#1]
Hello, really nice article, but there is one important point!

According to Nomicon https://doc.rust-lang.org/nomicon/ffi.html#ffi-and-panics 

>  A panic! across an FFI boundary is **undefined behavior**.

I don't say that article should dig so deep, but please add Note/warning that in real use all functions that are called from FFI should use catch_unwind and report errors to native code in other way.

Taking into account that it could be used with **any** user-provided impls of Write, that is fairly possible to encounter panics.

P.S. Rust's catch unwind is fairly cheap and creates small overhead in case no panic actually happen,

**Comment by Mart-Bogdan** [comment]
It seems the wrong place to post this issue. Reposted to Michael-F-Bryan/adventures.michaelfbryan.com#36

**Comment by Michael-F-Bryan** [comment]
I'm actually going to reopen this issue because making things exception-safe requires both code changes in this repository and an update to the article's wording.

**Comment by Michael-F-Bryan** [comment]
aaanndd it's closed again :stuck_out_tongue:
